## Linear Regression with Pandas dummies variable and OneHotEncoder

### load needed libraries and modules and DF

In [90]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn import linear_model

In [91]:
data =[
["monroe township",3000,565000],
["monroe township",3200,610000],
["monroe township",2600,550000],
["monroe township",3600,680000],
["monroe township",4000,725000],
["west windsor",2600,585000],
["west windsor",2800,615000],
["west windsor",3300,650000],
["west windsor",3600,710000],
["robinsville",2600,575000],
["robinsville",2900,600000],
["robinsville",3100,620000],
["robinsville",3600,695000],
]

data

[['monroe township', 3000, 565000],
 ['monroe township', 3200, 610000],
 ['monroe township', 2600, 550000],
 ['monroe township', 3600, 680000],
 ['monroe township', 4000, 725000],
 ['west windsor', 2600, 585000],
 ['west windsor', 2800, 615000],
 ['west windsor', 3300, 650000],
 ['west windsor', 3600, 710000],
 ['robinsville', 2600, 575000],
 ['robinsville', 2900, 600000],
 ['robinsville', 3100, 620000],
 ['robinsville', 3600, 695000]]

In [92]:
df = pd.DataFrame(data, columns=["Town" , "Area", "Price"])

In [93]:
df.to_csv("HousePrice.csv", index=False)
df

Town  Area   Price
0   monroe township  3000  565000
1   monroe township  3200  610000
2   monroe township  2600  550000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Town    13 non-null     object
 1   Area    13 non-null     int64 
 2   Price   13 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 444.0+ bytes


## #Model with pandas dummie variables

In [95]:
dummies = pd.get_dummies(df["Town"], dtype='int64')
dummies


monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [96]:
merged = pd.concat([df, dummies], axis='columns')
merged

Town  Area   Price  monroe township  robinsville  west windsor
0   monroe township  3000  565000                1            0             0
1   monroe township  3200  610000                1            0             0
2   monroe township  2600  550000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [97]:
final=merged.drop(["Town", "west windsor"], axis='columns')

In [98]:
final

Area   Price  monroe township  robinsville
0   3000  565000                1            0
1   3200  610000                1            0
2   2600  550000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [99]:
X=final.drop("Price", axis='columns')
y=final.Price
X

Area  monroe township  robinsville
0   3000                1            0
1   3200                1            0
2   2600                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [100]:
y

0     565000
1     610000
2     550000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: Price, dtype: int64

## Load a model and fit 

In [101]:
model1 = linear_model.LinearRegression()

In [102]:
model1.fit(X,y)

LinearRegression()

In [103]:
model1.predict([[3000,0,1]])

/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([616155.12792948])

In [104]:
model1.fit(X.values,y)

LinearRegression()

In [105]:
model1.predict([[3000,0,1]])

array([616155.12792948])

In [106]:
model1.predict([[3000,0,0]])

array([630482.69189422])

In [107]:
model1.predict([[2600,0,0]])

array([579723.71533005])

In [108]:
model1.score(X.values,y)

0.9573929037221873

In [109]:
model1.predict([[3400,0,0]])

array([681241.66845839])

In [110]:
model1.predict([[2800,0,1]])

array([590775.63964739])

## Model with OneHotEncoder()

In [111]:
from sklearn.preprocessing import LabelEncoder

In [112]:
le = LabelEncoder()

In [113]:
dfle = df
dfle
df

Town  Area   Price
0   monroe township  3000  565000
1   monroe township  3200  610000
2   monroe township  2600  550000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [114]:
dfle.Town = le.fit_transform(dfle.Town)

In [115]:
dfle

Town  Area   Price
0      0  3000  565000
1      0  3200  610000
2      0  2600  550000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [116]:
X=dfle[['Town','Area']].values
X

array([[   0, 3000],
       [   0, 3200],
       [   0, 2600],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [117]:
y=dfle.Price
y

0     565000
1     610000
2     550000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: Price, dtype: int64

### Since the latest build of sklearn library removed categorical_features parameter for onehotencoder class. It is advised to use ColumnTransformer class for categorical datasets. Refer the sklearn's official documentation for futher clarifications.

In [118]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct= ColumnTransformer([("Town", OneHotEncoder(), [0])], remainder = 'passthrough')

In [119]:
X

array([[   0, 3000],
       [   0, 3200],
       [   0, 2600],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [120]:

X=ct.fit_transform(X)


In [121]:

X

array([[1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [122]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [123]:
model1.fit(X,y)

LinearRegression()

In [124]:
model1.predict([[1,0,2800]])

array([590775.63964739])

In [125]:
model1.predict([[0,1,3400]])

array([681241.6684584])

## Exercise

In [126]:
data = [
["BMW X5",69000,18000,6],
["BMW X5",35000,34000,3],
["BMW X5",57000,26100,5],
["BMW X5",22500,40000,2],
["BMW X5",46000,31500,4],
["Audi A5",59000,29400,5],
["Audi A5",52000,32000,5],
["Audi A5",72000,19300,6],
["Audi A5",91000,12000,8],
["Mercedez Benz C class",67000,22000,6],
["Mercedez Benz C class",83000,20000,7],
["Mercedez Benz C class",79000,21000,7],
["Mercedez Benz C class",59000,33000,5],
]

In [127]:
data

[['BMW X5', 69000, 18000, 6],
 ['BMW X5', 35000, 34000, 3],
 ['BMW X5', 57000, 26100, 5],
 ['BMW X5', 22500, 40000, 2],
 ['BMW X5', 46000, 31500, 4],
 ['Audi A5', 59000, 29400, 5],
 ['Audi A5', 52000, 32000, 5],
 ['Audi A5', 72000, 19300, 6],
 ['Audi A5', 91000, 12000, 8],
 ['Mercedez Benz C class', 67000, 22000, 6],
 ['Mercedez Benz C class', 83000, 20000, 7],
 ['Mercedez Benz C class', 79000, 21000, 7],
 ['Mercedez Benz C class', 59000, 33000, 5]]

In [128]:
carlist = pd.DataFrame(data, columns=['Car', 'Mileage', 'Price', 'Age'])

In [129]:
carlist.to_csv("carPrice.csv", index=False)

In [130]:
carlist.Car = le.fit_transform(carlist['Car'])

In [131]:
carlist

Car  Mileage  Price  Age
0     1    69000  18000    6
1     1    35000  34000    3
2     1    57000  26100    5
3     1    22500  40000    2
4     1    46000  31500    4
5     0    59000  29400    5
6     0    52000  32000    5
7     0    72000  19300    6
8     0    91000  12000    8
9     2    67000  22000    6
10    2    83000  20000    7
11    2    79000  21000    7
12    2    59000  33000    5

In [132]:
X=carlist.drop('Price', axis='columns').values

In [133]:
y = carlist.Price

In [134]:
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [135]:
ct= ColumnTransformer([("Car", OneHotEncoder(), [0])], remainder = 'passthrough')


In [136]:
X=ct.fit_transform(X)

In [137]:
X=X[:,1:]

In [138]:
model2= linear_model.LinearRegression()

In [139]:
model2.fit(X,y)

LinearRegression()

In [140]:
model2.predict([[45000,4,0,0]])

array([-1.92743659e+08])

In [141]:
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [142]:
model2.predict([[0,0,45000,4]])

array([34537.77647335])

In [143]:
model2.predict([[0,1,86000,7]])

array([17818.95045785])